### ISSUE TITLE
`npm run build` in ./next-hardhat fails

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir-starter#24]
### Aim

Resolve the issue described in this thread: https://discord.com/channels/563037431604183070/1108319371832594442/1108476064742768781

### Expected behavior

It should work right out of the box.

### Bug

It should work right out of the box.

### To reproduce

Described in the discord thread.

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by critesjosh** [comment]
@signorecello wdyt?

**Comment by signorecello** [comment]
Answering in the discord thread..
