### ISSUE TITLE
Restructure next-hardhat

### ISSUE THREAD

**Issue by trangnv** [noir-lang/noir-starter#39]
### Problem

I think it's easier to structure a project (e.g. in `next-hardhat` or `with-foundry`) like this (my personal preference):
```bash
.
├── circuits
├── contracts
└── ui
```
whereas:
- `circuits` directory is where we write Noir program and test (with TS)
- `contracts` is for the solidity contracts testing, deployment, ...
- `ui` is for frontend

I feel the current one is kinda confusing, e.g. [this test](https://github.com/noir-lang/noir-starter/blob/main/next-hardhat/test/index.test.ts) contains both circuit and smart contract tests.

Again, this is only my preference, maybe there is a reason of having a lean project?

### Happy Case

Restructure both `next-hardhat` and `with-foundry` sub dirs

### Would you like to submit a PR for this Issue?

Yes

**Comment by signorecello** [comment]
thanks, moving to vite so structure has changed, thanks!
