### ISSUE TITLE
Merkle Proof calculation not verified on chain

### ISSUE THREAD

**Issue by tomoima525** [noir-lang/noir-starter#44]
### Aim

Merkle Proof computation is not working on chain even though the proof verification passes using api.acirVerifyProof

### Expected Behavior

It should verify on chain if api.acirVerifyProof is legit.

### Bug

<img width="1283" alt="image" src="https://github.com/noir-lang/noir-starter/assets/6277118/6ebef0cf-f74b-4770-a758-9e35a9064141">

### To Reproduce

Reproducible code and step

https://github.com/tomoima525/noir-starter/pull/1

### Environment

Local network (solidity)

### Would you like to submit a PR for this Issue?

No

**Comment by critesjosh** [comment]
i believe this is resolved now. feel free to reopen if not.
