### ISSUE TITLE
"nargo prove p" command not working in Foundry starter

### ISSUE THREAD

**Issue by PaulRBerg** [noir-lang/noir-starter#50]
I have followed all Foundry instructions up to the [Proof](https://github.com/noir-lang/noir-starter/tree/main/with-foundry#proof) command, which fails with this error:

> error: unexpected argument 'p' found

Nargo version:

```text
nargo 0.10.3 (git version hash: 2db759f43971c57e2f1f8284c82943e31a555d0c, is dirty: false)
```

**Comment by critesjosh** [comment]
thanks for flagging! updated via https://github.com/noir-lang/noir-starter/commit/d236cb66fae9b1e1418633f73ebfb2e219e22f2e
