### ISSUE TITLE
Switch to using `noir_js`

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir-starter#51]
```[tasklist]
### Helpful Prerequisite
- [ ] https://github.com/noir-lang/noir/issues/2711
```

### Problem

[noir-starter](https://github.com/noir-lang/noir-starter/) currently demonstrates the use of _acvm_js_, while the new _noir_js_ is [now released on NPM](https://www.npmjs.com/package/@noir-lang/noir_js) which could use a demonstration.

### Happy Case

Update noir-starter to use _noir_js_.

### Additional Context

_noir_js_ is currently a wrapper for _acvm_js_ and _noirc_abi_wasm_. _acvm_js_ is used for Noir program execution (i.e. witness generation) and _noirc_abi_wasm_ is a helper for encoding initial witness in preparation for execution / witness generation. 

The [compile_prove_verify.test.ts](https://github.com/noir-lang/noir/blob/5a3fb60140561ef0504cb86bd297d48eae82bf3b/compiler/integration-tests/test/integration/browser/compile_prove_verify.test.ts) is a great reference for how to make use of _noir_js_.

**Comment by critesjosh** [comment]
@signorecello can you take this one?

**Comment by Savio-Sou** [comment]
@signorecello good to call this closed with https://github.com/noir-lang/noir-starter/pull/54?

**Comment by signorecello** [comment]
yes sorry forgot to close it here
