### ISSUE TITLE
Deploy to netlify

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir-starter#6]
### Problem

Set up a build and deploy process so this reference repo is easily viewable on the web.

We can use this to verify that we dont merge any breaking changes to the main branch.

### Proposed solution

Set up deployment on netlify

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by signorecello** [comment]
closed with #11
