### ISSUE TITLE
Frontend fails to load files from circuit directory

### ISSUE THREAD

**Issue by shaddamciv** [noir-lang/noir-starter#7]
### Aim

Able to fork and get a working frontend

### Expected behavior

After forking template, installing and building expect the frontend to work by being able to prove the example case provided

### Bug

Gives a 500 error in network console for fetching files from circuit folder.

### To reproduce

1. npm i
2. npm run build:deploy
3. npm run dev
4. use 1,1 and Calculate proof

### Additional context

Changing the folder to circuits and circuits/src resolved the issue [opened PR in my own fork](https://github.com/shaddamciv/woofdash/pull/1/files)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by critesjosh** [comment]
thanks for flagging. this should work now. lmk if you run into any more issues
