### ISSUE TITLE
Check compatibility / Update to Noir `1.0.0-beta.0`

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir-starter#97]
As a pre-requisite to stable releasing Noir v1.0.0-beta.0 to a bigger audience, make sure we have a starter working with the version and is ready for recommendation to the community.

**Comment by TomAFrench** [comment]
@signorecello What's the status on this? This should be the last blocker on marking 1.0.0-beta.0 as stable.

**Comment by Savio-Sou** [comment]
> last blocker

More context is available in the Epic if helpful: https://github.com/AztecProtocol/dev-rel/issues/461

**Comment by signorecello** [comment]
Working on it! Should finish by tomorrow
